- id: 161779
  name: Poliisopreno_trans_633nm

- id: 161780
  name: PVA_mediaMM

- id: 161781
  name: PVA_altaMM

- id: 161782
  name: PE_glicol_mm4000

- id: 161783
  name: PE_glicol_mm10000

- id: 161784
  name: CeraDePolietileno-785nm

- id: 161785
  name: CeraDePolietileno-633nm

- id: 161786
  name: Poliisopreno_trans_785nm